#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# setup_proxy.sh
# Sets up an nginx reverse proxy for the Engine Vibration Monitor dashboard.
# Tested on Raspberry Pi OS (Bookworm/Bullseye) and Ubuntu 22.04+.
#
# Result: http://vibration-monitor.local  →  proxies to  localhost:7777
#
# Usage:
#   chmod +x setup_proxy.sh
#   sudo ./setup_proxy.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
APP_PORT=7777
NEW_HOSTNAME="vibration-monitor"
SITE_NAME="vibration-monitor"
DOMAIN="vibration-monitor.local"

# ── Root check ────────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    echo "✖  Please run as root: sudo $0"
    exit 1
fi

echo "──────────────────────────────────────────────────────────"
echo "  Engine Vibration Monitor — reverse proxy setup"
echo "  Hostname : $NEW_HOSTNAME"
echo "  Domain   : http://$DOMAIN"
echo "  Proxying : localhost:$APP_PORT"
echo "──────────────────────────────────────────────────────────"

# ── 1. Set hostname ──────────────────────────────────────────────────────────
echo ""
echo "[1/6] Setting hostname to '$NEW_HOSTNAME'…"
OLD_HOSTNAME="$(hostname)"
hostnamectl set-hostname "$NEW_HOSTNAME"
# Update /etc/hostname
echo "$NEW_HOSTNAME" > /etc/hostname
# Replace old hostname in /etc/hosts
sed -i "s/\b${OLD_HOSTNAME}\b/$NEW_HOSTNAME/g" /etc/hosts
# Ensure 127.0.1.1 entry exists (required for Debian/Raspberry Pi OS)
if grep -qE '^127\.0\.1\.1' /etc/hosts; then
    sed -i "s/^127\.0\.1\.1.*/127.0.1.1   $NEW_HOSTNAME/" /etc/hosts
else
    echo "127.0.1.1   $NEW_HOSTNAME" >> /etc/hosts
fi
echo "      Done: $(hostname)"

# ── 2. Install nginx ──────────────────────────────────────────────────────────
echo "[2/6] Installing nginx…"
apt-get update -qq
apt-get install -y nginx avahi-daemon

# ── 3. Write nginx site config ────────────────────────────────────────────────
echo "[3/6] Writing nginx site config…"
CONF="/etc/nginx/sites-available/$SITE_NAME"
cat > "$CONF" <<EOF
# Engine Vibration Monitor — nginx reverse proxy
# Generated by setup_proxy.sh on $(date '+%Y-%m-%d %H:%M:%S')

server {
    listen 80;
    server_name $DOMAIN $NEW_HOSTNAME ${NEW_HOSTNAME}.local localhost;

    # Proxy WebSocket upgrades (required for Dash live updates)
    location / {
        proxy_pass         http://127.0.0.1:$APP_PORT;
        proxy_http_version 1.1;

        proxy_set_header Upgrade    \$http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }
}
EOF

# ── 4. Enable site, disable default ───────────────────────────────────────────
echo "[4/6] Enabling site…"
ln -sf "$CONF" /etc/nginx/sites-enabled/"$SITE_NAME"
rm -f /etc/nginx/sites-enabled/default

nginx -t   # validate config

# ── 5. Add 127.0.0.1 alias for the domain (this machine only) ───────────────
echo "[5/6] Adding /etc/hosts alias for $DOMAIN…"
HOSTS_ENTRY="127.0.0.1   $DOMAIN"
if grep -qF "$DOMAIN" /etc/hosts; then
    echo "      (entry already exists — skipping)"
else
    echo "$HOSTS_ENTRY" >> /etc/hosts
    echo "      Added: $HOSTS_ENTRY"
fi

# ── 6. Enable & restart services ─────────────────────────────────────────────
echo "[6/6] Restarting nginx and avahi-daemon…"
systemctl enable  nginx
systemctl restart nginx
systemctl enable  avahi-daemon
systemctl restart avahi-daemon

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "──────────────────────────────────────────────────────────"
echo "  ✔  Setup complete!"
echo ""
echo "  Hostname set to : $NEW_HOSTNAME"
echo ""
echo "  Access the dashboard from:"
echo "    This machine   →  http://$DOMAIN"
echo "    This machine   →  http://localhost"
echo "    Any LAN device →  http://${NEW_HOSTNAME}.local"
echo ""
echo "  Make sure your app is running first:"
echo "    cd $(pwd) && ./run.sh"
echo "──────────────────────────────────────────────────────────"
